name: $(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r)

variables:
  - template: pipelines/vars.yml

trigger:
  branches:
    include:
      - trunk
      - feature/*

resources:
  - repo: self
    clean: "true"
    fetchDepth: "1"

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: pipelines/build.yml
  - template: pipelines/deploy.yml
